config/routes.rb
Rails.application.routes.draw do
  root 'signups#index'
  resources :signups

end

app/models/signup.rb
class Signup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :set_signup, only: [:show, :edit, :update, :destroy]


  # GET /signups
  # GET /signups.json
  def index
    @signups = Signup.all
  end

  # GET /signups/1
  # GET /signups/1.json
  def show
    @signups = Signup.all
  end

  # GET /signups/new
  def new
    @signups = Signup.all
    @signup = Signup.new
  end

  # GET /signups/1/edit
  def edit
    @signups = Signup.all
  end

  # POST /signups
  # POST /signups.json
  def create
    @signups = Signup.all
    @signup = Signup.new(signup_params)

    respond_to do |format|
      if @signup.save
        format.html { redirect_to @signup, notice: 'Signup was successfully created.' }
        format.json { render :show, status: :created, location: @signup }
        
      else
        format.html { render :new }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signups/1
  # PATCH/PUT /signups/1.json
  def update
    respond_to do |format|
      if @signup.update(signup_params)
        format.html { redirect_to @signup, notice: 'Signup was successfully updated.' }
        format.json { render :show, status: :ok, location: @signup }
      else
        format.html { render :edit }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signups/1
  # DELETE /signups/1.json
  def destroy
    @signups = Signup.all
    @signup.destroy
    respond_to do |format|
      format.html { redirect_to signups_url, notice: 'Signup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_signup
      @signups = Signup.all
      @signup = Signup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def signup_params
      @signups = Signup.all
      params.require(:signup).permit(:name, :size, :guest1, :size1, :guest2, :size2, :guest3, :size3, :guest4, :size4)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Barcrawl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Amatic+SC:400,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,700' rel='stylesheet' type='text/css'>
</head>
<body>
  <header id="header">

    <nav class="navbar navbar-inverse" role="navigation"><!-- add "wihite" class for white nav bar -->
        <div class="container">

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav navbar-left">
              <li><div class="clock">

              </div></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Sign Up!', new_signup_path %></li>
              <li><a href="#" data-toggle="modal" data-target="#myModal">Who is Attending?</a></li>

              <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <h4 class="modal-title" id="myModalLabel">List of Attendees</h4>
                    </div>
                    <div class="modal-body">
                      <table>
                        <thead>
                          <tr>
                            <th>Name</th>
                            <th>Shirt Size</th>
                            <th colspan="3"></th>
                          </tr>
                        </thead>

                        <tbody>
                          <% @signups.each do |signup| %>
                            <tr>
                              <td><%= signup.name %></td>
                              <td><%= signup.size %></td>
                            </tr>
                          <% end %>
                        </tbody>
                      </table>

                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            </ul>
          </div><!-- /.navbar-collapse -->

        </div>
      </nav>

  </header>
<%= yield %>

</body>
</html>

app/views/signups/_form.html.erb
<%= form_for(@signup) do |f| %>
  <% if @signup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@signup.errors.count, "error") %> prohibited this signup from being saved:</h2>
      <ul>
      <% @signup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name, "Full Name" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :size, "Shirt Size" %><br>
    <%= f.text_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/signups/edit.html.erb
<div class="container" id="newedit">
  <div class="row">
  <br>
    <h1>Edit Attendee</h1>
    <hr>
    <div class="col-lg-offset-4 col-lg-4">
      <%= render 'form' %>

      <%= link_to 'Back', signups_path %>
    </div>
  </div><!-- row -->
</div><!-- container -->

app/views/signups/index.html.erb
<link href='https://fonts.googleapis.com/css?family=Amatic+SC:400,700' rel='stylesheet' type='text/css'>

<div class="picture">
  <%= image_tag('image.png') %>
</div>

<div class="container" id="welcome">
  <div class="row">
  <br>
    <h1 class="centered">Welcome to the 1st Annual Christmahanakwanzika Pub Crawl</h1>
    <hr>

    <div class="col-lg-6">
      <p>The 1st annual Christmahanakwanzika Pub Crawl is set to go down Friday December 11, 2015 at 8:00 pm in downtown St. Petersburg, Florida. The first annual Master's pub crawl was a success and people were asking for an encore, and we are going to deliver. The Christmahanakwanzika Pub Crawl will take place over six bars, in which the route will be displayed online here shortly. We have created shirts for the event.  However, Joe lives off a teacher's salary and Chad just got out of school and is looking for work, and as much as we would love to buy everyone a shirt who attends we are unable to. We are poor. If you are interested in a shirt please let Joe or Chad know or sign up on the site before November 29, 2015(Sorry for the short notice!). Shirts will be $10.00 which will be due the date of the event. If you have any questions please contact us!    </p>
    </div><!-- col-lg-6 -->

    <div class="col-lg-6">
      <%= image_tag("shirt.png", height: '230', width: '45%')%>
    </div><!-- col-lg-6 -->

  </div><!-- row -->
</div><!-- container -->

<div class="container" id="route">
  <div class="row">
  <br>
    <h1 class="centered">The Route</h1>
    <hr>
    <div class="col-lg-offset-2 col-lg-8 ">
      <%= image_tag("map.png", height: '230', width: '40%')%>
      <p>
        We will start at the Yard of Ale at 8pm sharp.
        <br> As for the rest of the route, it is currently being discussed and will be available shortly.
      </p>
    </div>
  </div><!-- row -->
</div><!-- container -->

<div class="container" id="safety">
  <div class="row">
  <br>
    <h1 class="centered">SAFETY IS A PRIORITY</h1>
    <hr>

    <div class="col-lg-6 ">
      <h3>Transportation</h3>
      <h4 class="centered"><%= link_to "Uber", "https://www.uber.com/" %></h4>
      <h3>Shelter</h3>
      <h4 class="centered"><%= link_to "Hotel", "https://secure3.hilton.com/en_US/hi/reservation/book.htm?execution=e1s1" %></h4>
    </div><!-- col-lg-6 -->

    <div class="col-lg-6 ">
      <p> Safety is very important to us and a top priority. First off, we are all about having a good time and hope that each and everyone of you who attends does so.  Yet, if you plan to drink any alcohol, we ask that you do not drive. You are very important to us and would hate for this event adn your life to be ruined by an unfortunate event. We have constructed a few resources to help.<br>
         <br>Please use the resources as needed.
      </p>
    </div><!-- col-lg-6 -->

  </div><!-- row -->
</div><!-- container -->

<div class="container" id="contact">
  <div class="row">
  <br>
    <h1 class="centered">Contact Information</h1>
    <hr>
    <div class="col-lg-offset-2 col-lg-8 ">
      <h3>Joe Strickland</h3>
      <h4 class="centered">Phone:727-946-1582</h4>
      <h3>Chad Oakley</h3>
      <h4 class="centered">Phone:727-252-8238</h4>
    </div>
  </div><!-- row -->
</div><!-- container -->

app/views/signups/new.html.erb
<div class="container" id="newedit">
  <div class="row">
  <br>
    <h1 class="centered">Hell Yes! Excited to see you on Dec. 11th.</h1>
    <hr>
    <div class="col-lg-offset-4 col-lg-4">
      <h4>Please take your time filling out the form.  Once completed you will be unable to delete any information. If you need to edit any information please contact Joe or Chad.</h4>
      <%= render 'form' %>

      <%= link_to 'Back', signups_path %>
    </div>

  </div><!-- row -->
</div><!-- container -->

app/views/signups/show.html.erb
<div class="container" id="newedit">
  <div class="row">
  <br>
    <h1 class="centered">Get Ready To Party!</h1>
    <hr>
    <div class="col-lg-offset-4 col-lg-4">
      <p>
        <strong>Name:</strong>
        <%= @signup.name %>
      </p>

      <p>
        <strong>Size:</strong>
        <%= @signup.size %>
      </p>

      <%= link_to 'Edit', edit_signup_path(@signup) %> |
      <%= link_to 'Back', signups_path %>
    </div>

  </div><!-- row -->
</div><!-- container --><p id="notice"><%= notice %></p>